### ISSUE TITLE
FireGestureRecognizer error

### ISSUE THREAD

**Issue by HieuLsw** [nicklockwood/FPSControls#1]
startTimes[touch.hash] = touch.timestamp : NSobject does not have a member named timestamp
            let newPos = touch.locationInView(view) : NSobject does not have a member named locationInView
            let oldPos = touch.previousLocationInView(view): NSobject does not have a member named :previousLocationInView
 v..v.v

**Comment by HieuLsw** [comment]
can you help me ? @nicklockwood

**Comment by nicklockwood** [comment]
Sorry about that, should be fixed in 1.0.1
